Watching for file changes with StatReloader
C:\Users\Лидия\Desktop\Django\djcourse\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Лидия\Desktop\Django\djcourse\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\Лидия\Desktop\Django\djcourse\firstapp\views.py changed, reloading.
Watching for file changes with StatReloader
INFO 2024-04-05 13:16:17,733 autoreload 18676 15928 Watching for file changes with StatReloader
INFO 2024-04-06 20:12:30,005 autoreload 21396 9892 Watching for file changes with StatReloader
ERROR 2024-04-06 20:13:57,646 log 21396 11368 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 7, in client_orders_week
    date = datetime.now()
           ^^^^^^^^^^^^
AttributeError: module 'datetime' has no attribute 'now'
ERROR 2024-04-06 20:13:57,651 basehttp 21396 11368 "GET /secondapp/week/20 HTTP/1.1" 500 75358
WARNING 2024-04-06 20:13:58,356 log 21396 11368 Not Found: /favicon.ico
WARNING 2024-04-06 20:13:58,357 basehttp 21396 11368 "GET /favicon.ico HTTP/1.1" 404 2429
INFO 2024-04-06 20:14:41,831 autoreload 21396 9892 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:14:42,403 autoreload 1944 11140 Watching for file changes with StatReloader
INFO 2024-04-06 20:14:53,058 autoreload 1944 11140 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:14:53,599 autoreload 10576 18572 Watching for file changes with StatReloader
INFO 2024-04-06 20:14:55,015 autoreload 10576 18572 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:14:55,539 autoreload 24832 9148 Watching for file changes with StatReloader
INFO 2024-04-06 20:14:58,850 autoreload 24832 9148 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:14:59,379 autoreload 24136 19160 Watching for file changes with StatReloader
INFO 2024-04-06 20:15:09,141 autoreload 24136 19160 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:15:09,739 autoreload 18248 24544 Watching for file changes with StatReloader
INFO 2024-04-06 20:15:13,276 autoreload 18248 24544 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:15:13,920 autoreload 21812 12516 Watching for file changes with StatReloader
ERROR 2024-04-06 20:15:15,407 log 21812 13308 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 10, in client_orders_week
    orders = Order.objects.filter(customer=client, date_order__lte=new_date).order_by('-date_order')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:15:15,416 basehttp 21812 13308 "GET /secondapp/week/20 HTTP/1.1" 500 123789
INFO 2024-04-06 20:16:34,493 autoreload 21812 12516 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:16:35,043 autoreload 2328 21816 Watching for file changes with StatReloader
INFO 2024-04-06 20:16:37,554 autoreload 2328 21816 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:16:38,089 autoreload 18900 14916 Watching for file changes with StatReloader
INFO 2024-04-06 20:16:39,529 autoreload 18900 14916 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:16:40,034 autoreload 22568 3056 Watching for file changes with StatReloader
INFO 2024-04-06 20:16:47,715 autoreload 22568 3056 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:16:48,359 autoreload 25992 11676 Watching for file changes with StatReloader
ERROR 2024-04-06 20:16:49,851 log 25992 12092 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 10, in client_orders_week
    orders = Order.objects.filter(customer=client).order_by('-date_order')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 2253, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:16:49,856 basehttp 25992 12092 "GET /secondapp/week/20 HTTP/1.1" 500 91525
INFO 2024-04-06 20:16:56,237 autoreload 25992 11676 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:16:56,754 autoreload 3176 20180 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:01,275 autoreload 3176 20180 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:01,938 autoreload 14260 20952 Watching for file changes with StatReloader
ERROR 2024-04-06 20:17:03,468 log 14260 16720 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 10, in client_orders_week
    orders = Order.objects.filter(customer=client, date_order__lte=new_date)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:17:03,478 basehttp 14260 16720 "GET /secondapp/week/20 HTTP/1.1" 500 123710
INFO 2024-04-06 20:17:09,740 autoreload 14260 20952 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:10,479 autoreload 22872 21712 Watching for file changes with StatReloader
ERROR 2024-04-06 20:17:12,146 log 22872 21128 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 847, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for order in {{ orders }}
ERROR 2024-04-06 20:17:12,176 basehttp 22872 21128 "GET /secondapp/week/20 HTTP/1.1" 500 180698
INFO 2024-04-06 20:17:23,590 autoreload 22872 21712 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:24,111 autoreload 9308 16976 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:27,568 autoreload 9308 16976 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:28,241 autoreload 19476 8528 Watching for file changes with StatReloader
ERROR 2024-04-06 20:17:29,631 log 19476 17244 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 10, in client_orders_week
    orders = Order.objects.filter(customer=client).order_by('-date_order')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 2253, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:17:29,637 basehttp 19476 17244 "GET /secondapp/week/20 HTTP/1.1" 500 91525
INFO 2024-04-06 20:17:35,075 autoreload 19476 8528 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:35,595 autoreload 16120 3980 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:37,004 autoreload 16120 3980 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:37,514 autoreload 13972 7612 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:38,905 autoreload 13972 7612 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:39,446 autoreload 18348 7200 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:43,987 autoreload 18348 7200 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:44,501 autoreload 1932 10000 Watching for file changes with StatReloader
INFO 2024-04-06 20:17:46,921 autoreload 1932 10000 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:17:47,425 autoreload 6320 6776 Watching for file changes with StatReloader
ERROR 2024-04-06 20:18:00,609 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 847, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for order in {{ orders }}
ERROR 2024-04-06 20:18:00,618 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 180696
ERROR 2024-04-06 20:19:10,245 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 847, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for product in {{ order.products }}
ERROR 2024-04-06 20:19:10,254 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 195998
ERROR 2024-04-06 20:19:26,226 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-06 20:19:26,233 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 143992
ERROR 2024-04-06 20:20:09,258 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-06 20:20:09,267 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 143990
ERROR 2024-04-06 20:20:10,555 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-06 20:20:10,565 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 143992
ERROR 2024-04-06 20:20:11,415 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 63, in render
    reraise(exc, self.backend)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
ERROR 2024-04-06 20:20:11,422 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 143992
ERROR 2024-04-06 20:20:51,829 log 6320 24664 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2024-04-06 20:20:51,838 basehttp 6320 24664 "GET /secondapp/week/20 HTTP/1.1" 500 170929
ERROR 2024-04-06 20:22:34,334 log 6320 5448 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 847, in do_for
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for order in { orders }
ERROR 2024-04-06 20:22:34,343 basehttp 6320 5448 "GET /secondapp/week/20 HTTP/1.1" 500 180668
ERROR 2024-04-06 20:24:46,304 log 6320 10260 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 11, in client_orders_week
    return render(request, 'secondapp/sorted_orders.html', {'client': client, 'orders': orders})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\template\defaulttags.py", line 197, in render
    values = list(values)
             ^^^^^^^^^^^^
TypeError: 'ManyRelatedManager' object is not iterable
ERROR 2024-04-06 20:24:46,314 basehttp 6320 10260 "GET /secondapp/week/20 HTTP/1.1" 500 170929
INFO 2024-04-06 20:26:06,499 autoreload 6320 6776 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:07,448 autoreload 10808 9040 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:12,028 autoreload 10808 9040 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:12,557 autoreload 13460 2164 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:27,489 autoreload 13460 2164 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:28,059 autoreload 13932 7660 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:29,533 autoreload 13932 7660 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:30,047 autoreload 5328 13896 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:38,767 autoreload 5328 13896 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:39,284 autoreload 9652 20680 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:50,979 autoreload 9652 20680 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:51,474 autoreload 21924 23084 Watching for file changes with StatReloader
INFO 2024-04-06 20:26:56,112 autoreload 21924 23084 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:26:56,619 autoreload 23256 16784 Watching for file changes with StatReloader
INFO 2024-04-06 20:27:13,834 autoreload 23256 16784 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:27:14,391 autoreload 23632 1340 Watching for file changes with StatReloader
INFO 2024-04-06 20:27:18,967 autoreload 23632 1340 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:27:19,468 autoreload 12416 8352 Watching for file changes with StatReloader
INFO 2024-04-06 20:27:26,204 autoreload 12416 8352 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:27:26,987 autoreload 12004 18480 Watching for file changes with StatReloader
INFO 2024-04-06 20:28:25,669 autoreload 12004 18480 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:28:26,207 autoreload 19920 16196 Watching for file changes with StatReloader
INFO 2024-04-06 20:28:28,678 autoreload 19920 16196 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:28:29,219 autoreload 25584 2072 Watching for file changes with StatReloader
INFO 2024-04-06 20:28:36,717 autoreload 25584 2072 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:28:37,268 autoreload 12240 15492 Watching for file changes with StatReloader
INFO 2024-04-06 20:28:47,021 autoreload 12240 15492 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:28:47,931 autoreload 8144 7472 Watching for file changes with StatReloader
INFO 2024-04-06 20:28:49,183 autoreload 8144 7472 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:28:49,726 autoreload 23140 10508 Watching for file changes with StatReloader
INFO 2024-04-06 20:29:55,014 autoreload 23140 10508 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:29:55,618 autoreload 5004 1112 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:10,734 autoreload 5004 1112 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:11,355 autoreload 21960 10188 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:14,954 autoreload 21960 10188 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:15,522 autoreload 25468 14208 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:17,761 autoreload 25468 14208 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:18,273 autoreload 8188 12392 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:24,913 autoreload 8188 12392 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:25,452 autoreload 16432 10660 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:26,674 autoreload 16432 10660 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:27,207 autoreload 5088 156 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:28,670 autoreload 5088 156 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:29,200 autoreload 18576 15168 Watching for file changes with StatReloader
INFO 2024-04-06 20:30:30,625 autoreload 18576 15168 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:30:31,138 autoreload 8384 21652 Watching for file changes with StatReloader
INFO 2024-04-06 20:31:21,237 autoreload 8384 21652 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:31:21,727 autoreload 24524 15720 Watching for file changes with StatReloader
INFO 2024-04-06 20:31:35,371 autoreload 24524 15720 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:31:35,896 autoreload 24908 6916 Watching for file changes with StatReloader
INFO 2024-04-06 20:31:46,724 autoreload 24908 6916 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:31:47,279 autoreload 15328 25532 Watching for file changes with StatReloader
INFO 2024-04-06 20:31:49,518 autoreload 15328 25532 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:31:50,001 autoreload 18588 16704 Watching for file changes with StatReloader
INFO 2024-04-06 20:32:03,735 autoreload 18588 16704 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:32:04,290 autoreload 15144 11736 Watching for file changes with StatReloader
INFO 2024-04-06 20:32:11,694 autoreload 15144 11736 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:32:12,224 autoreload 7200 21392 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:28,986 autoreload 7200 21392 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:30,205 autoreload 26376 26416 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:31,442 autoreload 26376 26416 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:31,962 autoreload 6604 3320 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:33,361 autoreload 6604 3320 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:33,890 autoreload 17476 26576 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:37,465 autoreload 17476 26576 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:38,009 autoreload 8996 19660 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:39,399 autoreload 8996 19660 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:39,916 autoreload 23348 20944 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:44,440 autoreload 23348 20944 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:45,676 autoreload 3092 19208 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:46,895 autoreload 3092 19208 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:47,428 autoreload 10212 15308 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:48,890 autoreload 10212 15308 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:49,417 autoreload 22840 14356 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:50,657 autoreload 22840 14356 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:51,139 autoreload 24416 10460 Watching for file changes with StatReloader
INFO 2024-04-06 20:34:53,600 autoreload 24416 10460 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:34:54,204 autoreload 9100 25484 Watching for file changes with StatReloader
INFO 2024-04-06 20:35:54,364 autoreload 9100 25484 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:35:54,908 autoreload 1516 1288 Watching for file changes with StatReloader
INFO 2024-04-06 20:35:56,166 autoreload 1516 1288 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:35:56,663 autoreload 23952 24344 Watching for file changes with StatReloader
INFO 2024-04-06 20:35:59,142 autoreload 23952 24344 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:35:59,637 autoreload 10864 7040 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:03,188 autoreload 10864 7040 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:03,724 autoreload 22444 14492 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:09,141 autoreload 22444 14492 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:09,663 autoreload 1700 6312 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:10,876 autoreload 1700 6312 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:11,364 autoreload 9448 12148 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:23,087 autoreload 9448 12148 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:23,581 autoreload 6356 19144 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:34,186 autoreload 6356 19144 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:34,683 autoreload 25244 19308 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:45,277 autoreload 25244 19308 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:45,790 autoreload 9380 24064 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:48,033 autoreload 9380 24064 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:48,548 autoreload 9440 16592 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:50,499 autoreload 9440 16592 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:51,051 autoreload 21604 2308 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:53,292 autoreload 21604 2308 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:53,855 autoreload 5652 6424 Watching for file changes with StatReloader
INFO 2024-04-06 20:36:59,225 autoreload 5652 6424 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:36:59,741 autoreload 17424 21296 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:05,097 autoreload 17424 21296 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:05,609 autoreload 20536 11828 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:08,905 autoreload 20536 11828 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:09,408 autoreload 6932 9776 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:17,909 autoreload 6932 9776 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:18,392 autoreload 8120 7488 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:22,754 autoreload 8120 7488 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:23,259 autoreload 22340 11356 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:27,811 autoreload 22340 11356 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:28,320 autoreload 14464 9812 Watching for file changes with StatReloader
INFO 2024-04-06 20:37:29,718 autoreload 14464 9812 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:37:31,753 autoreload 14412 9476 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:35,501 autoreload 14412 9476 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:36,962 autoreload 8680 23900 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:38,573 autoreload 8680 23900 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:39,111 autoreload 20808 8592 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:41,584 autoreload 20808 8592 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:42,128 autoreload 23216 6304 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:46,624 autoreload 23216 6304 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:47,111 autoreload 10796 1144 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:49,364 autoreload 10796 1144 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:49,902 autoreload 25076 25928 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:52,441 autoreload 25076 25928 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:52,970 autoreload 17880 14392 Watching for file changes with StatReloader
INFO 2024-04-06 20:39:54,419 autoreload 17880 14392 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:39:54,931 autoreload 17244 4044 Watching for file changes with StatReloader
INFO 2024-04-06 20:40:21,561 autoreload 17244 4044 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:40:22,095 autoreload 20532 25124 Watching for file changes with StatReloader
INFO 2024-04-06 20:40:49,810 autoreload 20532 25124 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:40:50,309 autoreload 16612 12196 Watching for file changes with StatReloader
INFO 2024-04-06 20:41:02,131 autoreload 16612 12196 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:41:02,649 autoreload 23248 6416 Watching for file changes with StatReloader
INFO 2024-04-06 20:41:05,099 autoreload 23248 6416 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:41:05,680 autoreload 25472 19036 Watching for file changes with StatReloader
INFO 2024-04-06 20:41:48,054 autoreload 25472 19036 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:41:48,706 autoreload 21064 10436 Watching for file changes with StatReloader
ERROR 2024-04-06 20:41:51,998 log 21064 3340 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 13, in client_orders_week
    products = Order.objects.filter(order=order)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:41:52,006 basehttp 21064 3340 "GET /secondapp/week/20 HTTP/1.1" 500 122587
INFO 2024-04-06 20:44:55,110 autoreload 21064 10436 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:44:55,633 autoreload 24196 12352 Watching for file changes with StatReloader
INFO 2024-04-06 20:44:57,082 autoreload 24196 12352 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:44:57,681 autoreload 11988 4856 Watching for file changes with StatReloader
INFO 2024-04-06 20:45:07,295 basehttp 11988 11384 "GET /secondapp/week/20 HTTP/1.1" 200 299
INFO 2024-04-06 20:47:29,112 autoreload 11988 4856 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:47:29,624 autoreload 10064 17636 Watching for file changes with StatReloader
INFO 2024-04-06 20:48:03,583 autoreload 10064 17636 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:48:04,084 autoreload 25320 14108 Watching for file changes with StatReloader
INFO 2024-04-06 20:48:30,573 autoreload 25320 14108 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:48:31,132 autoreload 1440 16144 Watching for file changes with StatReloader
ERROR 2024-04-06 20:48:36,558 log 1440 16416 Internal Server Error: /secondapp/week/20
Traceback (most recent call last):
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py", line 10, in client_orders_week
    orders = Order.objects.filter(customer=client, date_order__gte=new_date).order_by('-date_ordered')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Лидия\Desktop\Django\venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_order' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
ERROR 2024-04-06 20:48:36,564 basehttp 1440 16416 "GET /secondapp/week/20 HTTP/1.1" 500 123806
INFO 2024-04-06 20:48:52,663 autoreload 1440 16144 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:48:53,180 autoreload 14220 15100 Watching for file changes with StatReloader
INFO 2024-04-06 20:48:53,490 basehttp 14220 15916 "GET /secondapp/week/20 HTTP/1.1" 200 299
INFO 2024-04-06 20:49:31,487 autoreload 14220 15100 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:49:32,012 autoreload 10212 19096 Watching for file changes with StatReloader
INFO 2024-04-06 20:49:54,504 autoreload 10212 19096 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:49:55,065 autoreload 16256 21716 Watching for file changes with StatReloader
INFO 2024-04-06 20:50:26,944 autoreload 16256 21716 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:50:27,487 autoreload 21852 5096 Watching for file changes with StatReloader
INFO 2024-04-06 20:50:31,024 autoreload 21852 5096 C:\Users\Лидия\Desktop\Django\djcourse\secondapp\views.py changed, reloading.
INFO 2024-04-06 20:50:31,570 autoreload 19032 1516 Watching for file changes with StatReloader
INFO 2024-04-06 20:53:00,142 basehttp 19032 2276 "GET /secondapp/week/20 HTTP/1.1" 200 299
INFO 2024-04-06 20:53:23,514 basehttp 19032 16176 "GET /secondapp/week/20 HTTP/1.1" 200 299
INFO 2024-04-06 20:53:24,965 basehttp 19032 16176 "GET /secondapp/week/20 HTTP/1.1" 200 299
